/* eslint-disable no-shadow */
/* eslint-disable no-unused-vars */

import {
  BACKSPACE_CHARACTER,
  CLEAN_CHARACTER,
  EVALUATE_CHARACTER,
} from "../constants/pages/index_page_constants";
import {
  ADDITION_CHARACTER,
  DIVISION_CHARACTER,
  EIGHT_CHARACTER,
  FIVE_CHARACTER,
  FOUR_CHARACTER,
  MULTIPLICATION_CHARACTER,
  NINE_CHARACTER,
  ONE_CHARACTER,
  POINT_CHARACTER,
  SEVEN_CHARACTER,
  SIX_CHARACTER,
  SUBTRACTION_CHARACTER,
  THREE_CHARACTER,
  TWO_CHARACTER,
  ZERO_CHARACTER,
} from "../constants/domains/calculator/calculator_character_values_constants";

enum UiCalculatorCharacters {
  DIVISION = DIVISION_CHARACTER,
  MULTIPLICATION = MULTIPLICATION_CHARACTER,
  SEVEN = SEVEN_CHARACTER,
  EIGHT = EIGHT_CHARACTER,
  NINE = NINE_CHARACTER,
  ADDITION = ADDITION_CHARACTER,
  FOUR = FOUR_CHARACTER,
  FIVE = FIVE_CHARACTER,
  SIX = SIX_CHARACTER,
  SUBTRACTION = SUBTRACTION_CHARACTER,
  ONE = ONE_CHARACTER,
  TWO = TWO_CHARACTER,
  THREE = THREE_CHARACTER,
  ZERO = ZERO_CHARACTER,
  POINT = POINT_CHARACTER,
  CLEAN = CLEAN_CHARACTER,
  BACKSPACE = BACKSPACE_CHARACTER,
  EVALUATE = EVALUATE_CHARACTER,
}

export default UiCalculatorCharacters;
